version: '3'
services:
  streamer:
    build: ./streamer_service/
    networks:
      - hadoop
    ports:
      - 1337:1337
    
  hadoop-master:
    build: ./master/
    container_name: hadoop-master
    hostname: hadoop-master
    # tty: true
    ports:
      - 9870:9870
      - 8088:8088
      - 7077:7077
      - 16010:16010
    networks:
      hadoop:

  hadoop-worker1:
    build: ./worker/
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    # tty: true
    ports:
      - 8040:8042
    networks:
      hadoop:

  hadoop-worker2:
    build: ./worker/
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    # tty: true
    ports:
      - 8041:8042
    networks:
      hadoop:

networks:
  hadoop:
    driver: bridge
